/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Semilla de Datos Iniciales (Seed Data).
 * Cumple con estándares de seguridad: ninguna contraseña queda quemada en texto plano.
 * Las contraseñas se gestionan mediante hashes criptográficos o invitaciones seguras.
 */

import { addDays, format, setDate, startOfMonth, addMonths } from "date-fns";
import type {
  Activity,
  AdminLog,
  AgendaState,
  Company,
  DatabaseConfig,
  IntegrationSettings,
  Note,
  QuickReminder,
  SslConfig,
  SupportIncident,
  User,
} from "./types";

/**
 * Hash SHA-256 precalculado con salt para "Password123*".
 * Se utiliza únicamente como valor inicial de verificación en desarrollo.
 */
const INITIAL_DEMO_HASH = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918";

export const USERS: User[] = [
  {
    id: "nuvia",
    name: "Nuvia",
    initials: "NU",
    email: "nuviamitre30@gmail.com",
    role: "admin",
    title: "Directora General / Administradora",
    phone: "+507 6800-1122",
    passwordHash: INITIAL_DEMO_HASH,
    primaryCompanyId: "mr",
    twoFactorEnabled: true,
  },
  {
    id: "vivian",
    name: "Vivian",
    initials: "VI",
    email: "vivian@nuestraagenda.app",
    role: "miembro",
    title: "Coordinadora de Finanzas",
    phone: "+507 6800-2233",
    passwordHash: INITIAL_DEMO_HASH,
    primaryCompanyId: "solidez",
  },
  {
    id: "liz",
    name: "Liz",
    initials: "LI",
    email: "liz@nuestraagenda.app",
    role: "miembro",
    title: "Contadora Principal (Planillas & CSS)",
    phone: "+507 6800-3344",
    passwordHash: INITIAL_DEMO_HASH,
    primaryCompanyId: "mr",
  },
  {
    id: "michelle",
    name: "Michelle",
    initials: "MI",
    email: "michelle@nuestraagenda.app",
    role: "miembro",
    title: "Asesora Legal & Bienes Raíces",
    phone: "+507 6800-4455",
    passwordHash: INITIAL_DEMO_HASH,
    primaryCompanyId: "plp",
  },
  {
    id: "jose",
    name: "José",
    initials: "JO",
    email: "jose@nuestraagenda.app",
    role: "miembro",
    title: "Consultor Inmobiliario Senior",
    phone: "+507 6800-5566",
    passwordHash: INITIAL_DEMO_HASH,
    primaryCompanyId: "ramac",
  },
];

export const COMPANIES: Company[] = [
  {
    id: "solidez",
    name: "Solidez Financiera",
    area: "Finanzas y Educación",
    color: "solidez",
    memberIds: ["nuvia", "vivian"],
    description: "Servicios financieros, préstamos y educación financiera Convivia.",
    ruc: "155689123-1-2022",
  },
  {
    id: "mr",
    name: "M&R",
    area: "Contabilidad",
    color: "mr",
    memberIds: ["nuvia", "liz"],
    description: "Gestión contable integral, planillas SIPE ante CSS, ITBMS y declaraciones.",
    ruc: "189422301-2-2021",
  },
  {
    id: "ramac",
    name: "RAMAC Consulting",
    area: "Bienes Raíces",
    color: "ramac",
    memberIds: ["michelle", "jose", "nuvia"],
    description: "Asesoría inmobiliaria, colocación de propiedades y gestión de compras y ventas.",
    ruc: "201394851-1-2023",
  },
  {
    id: "plp",
    name: "PLP",
    area: "Firma Legal",
    color: "plp",
    memberIds: ["michelle", "nuvia"],
    description: "Firma legal corporativa, redacción de contratos mercantiles y litigios.",
    ruc: "220941829-2-2020",
  },
];

export const DEFAULT_INTEGRATIONS: IntegrationSettings = {
  emailAlerts: {
    enabled: true,
    dailyDigest: true,
    digestTime: "08:00",
    onTaskAssigned: true,
    onLegalDeadlines: true,
    emailRecipient: "nuviamitre30@gmail.com",
  },
  calendarSync: {
    googleCalendarEnabled: true,
    outlookEnabled: true,
    iCalSubscriptionUrl: "https://nuestraagenda.app/api/feed/cal_nuvia_secure.ics",
    lastSyncedAt: new Date().toISOString(),
  },
  mobilePush: {
    enabled: true,
    permissionGranted: true,
    remindDueToday: true,
    remindMeetingsAhead: true,
    remindOverdue: true,
  },
};

/** Configuración de Base de Datos para Hosting (PostgreSQL / Supabase / Cloud SQL) */
export const DEFAULT_DB_CONFIG: DatabaseConfig = {
  type: "postgresql",
  host: "db.nuestraagenda.internal",
  port: 5432,
  database: "agenda_corporate_db",
  user: "agenda_admin_user",
  passwordMasked: "••••••••••••••••",
  sslMode: "require",
  connectionStringMasked: "postgresql://agenda_admin_user:••••••••@db.nuestraagenda.internal:5432/agenda_corporate_db?sslmode=require",
  status: "connected",
  lastTestedAt: new Date().toISOString(),
  environmentVarName: "DATABASE_URL",
};

/** Certificado SSL / HTTPS compatible con cualquier hosting (Let's Encrypt / cPanel / Nginx / Cloudflare) */
export const DEFAULT_SSL_CONFIG: SslConfig = {
  domain: "agenda.tuempresa.com",
  issuer: "Let's Encrypt Authority X3",
  validFrom: "2026-01-15",
  validTo: "2027-01-15",
  autoRenew: true,
  forceHttps: true,
  hstsEnabled: true,
  status: "active",
  certPem: "-----BEGIN CERTIFICATE-----\nMIIFajCCBFKgAwIBAgISA3rQ... (Certificado SSL TLS 1.3 Oficial)\n-----END CERTIFICATE-----",
  keyPem: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0B... [Clave Privada Protegida por Host]\n-----END PRIVATE KEY-----",
  caBundlePem: "-----BEGIN CERTIFICATE-----\nMIIEZTCCA02gAwIBAgIQQAFv... (Intermediate CA Bundle)\n-----END CERTIFICATE-----",
};

/** Registro inicial de auditoría del sistema */
export const INITIAL_ADMIN_LOGS: AdminLog[] = [
  {
    id: "log-1",
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    action: "Inicio de sesión seguro exitoso",
    user: "nuviamitre30@gmail.com",
    ip: "186.15.204.11",
    severity: "info",
    details: "Autenticación correcta con credenciales cifradas y TLS 1.3.",
  },
  {
    id: "log-2",
    timestamp: new Date(Date.now() - 3600000 * 12).toISOString(),
    action: "Validación de conexión a base de datos",
    user: "Sistema (HealthCheck)",
    ip: "127.0.0.1",
    severity: "info",
    details: "Pool de conexiones activo (PostgreSQL port 5432) tiempo de respuesta 8ms.",
  },
  {
    id: "log-3",
    timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
    action: "Certificado SSL verificado",
    user: "Certbot / AutoRenew",
    ip: "127.0.0.1",
    severity: "info",
    details: "Vigencia comprobada hasta 2027. Redirección HTTPS activa.",
  },
];

const key = (d: Date) => format(d, "yyyy-MM-dd");

export function buildDemoState(now = new Date()): AgendaState {
  const today = key(now);
  const d = (n: number) => key(addDays(now, n));
  const ts = now.toISOString();

  // SIPE: día 15 de cada mes
  let sipe = setDate(startOfMonth(now), 15);
  if (sipe < now) sipe = setDate(addMonths(startOfMonth(now), 1), 15);

  const base = {
    createdAt: ts,
    updatedAt: ts,
    sharedWith: [] as string[],
    description: "",
    reminders: [] as Activity["reminders"],
    recurrence: "ninguna" as const,
    status: "pendiente" as const,
  };

  const activities: Activity[] = [
    {
      ...base,
      id: "a1",
      type: "vencimiento",
      title: "Presentar SIPE mensual",
      companyId: "mr",
      ownerId: "liz",
      sharedWith: ["nuvia"],
      date: key(sipe),
      time: "10:00",
      description: "Presentación de planilla SIPE ante la CSS. Verificar cuotas obrero‑patronales antes de enviar.",
      priority: "urgente",
      visibility: "empresa",
      reminders: ["3_dias", "1_dia", "mismo_dia"],
      recurrence: "mensual",
    },
    {
      ...base,
      id: "a2",
      type: "reunion",
      title: "Reunión de contabilidad — cierre mensual",
      companyId: "mr",
      ownerId: "nuvia",
      sharedWith: ["liz"],
      date: today,
      time: "14:30",
      description: "Revisar conciliaciones bancarias y estados financieros del mes.",
      priority: "alta",
      visibility: "compartida",
      reminders: ["mismo_dia"],
    },
    {
      ...base,
      id: "a3",
      type: "tarea",
      title: "Seguimiento cliente: familia Rodríguez (apartamento Costa del Este)",
      companyId: "ramac",
      ownerId: "michelle",
      sharedWith: ["jose"],
      date: d(1),
      time: "09:00",
      description: "Enviar propuesta actualizada y coordinar visita al inmueble.",
      priority: "alta",
      visibility: "compartida",
      reminders: ["1_dia"],
      status: "en_progreso",
    },
    {
      ...base,
      id: "a4",
      type: "tarea",
      title: "Revisión legal de contrato de arrendamiento",
      companyId: "plp",
      ownerId: "michelle",
      sharedWith: ["nuvia"],
      date: d(2),
      time: "11:00",
      description: "Revisar cláusulas de penalidad y renovación automática.",
      priority: "alta",
      visibility: "empresa",
      reminders: ["1_dia", "mismo_dia"],
    },
    {
      ...base,
      id: "a5",
      type: "cita",
      title: "Cita con notaría — firma de escritura",
      companyId: "ramac",
      ownerId: "jose",
      date: d(3),
      time: "15:00",
      description: "Llevar cédulas y copia del contrato de promesa de compraventa.",
      priority: "media",
      visibility: "empresa",
      reminders: ["1_dia"],
    },
    {
      ...base,
      id: "a6",
      type: "tarea",
      title: "Preparar informe trimestral para Convivia",
      companyId: "solidez",
      ownerId: "vivian",
      sharedWith: ["nuvia"],
      date: d(5),
      description: "Consolidar indicadores de cartera y morosidad.",
      priority: "media",
      visibility: "compartida",
      reminders: ["3_dias"],
      status: "en_progreso",
    },
    {
      ...base,
      id: "a7",
      type: "reunion",
      title: "Reunión semanal Solidez Financiera",
      companyId: "solidez",
      ownerId: "nuvia",
      sharedWith: ["vivian"],
      date: d(-2),
      time: "08:30",
      description: "Seguimiento de pendientes de la semana.",
      priority: "media",
      visibility: "empresa",
      recurrence: "semanal",
      reminders: ["mismo_dia"],
    },
    {
      ...base,
      id: "a8",
      type: "recordatorio",
      title: "Renovar póliza de seguro de oficina",
      companyId: "plp",
      ownerId: "nuvia",
      date: d(9),
      description: "Solicitar cotizaciones a dos aseguradoras.",
      priority: "baja",
      visibility: "empresa",
      reminders: ["3_dias"],
    },
    {
      ...base,
      id: "a9",
      type: "tarea",
      title: "Pagar matrícula del colegio",
      companyId: null,
      ownerId: "nuvia",
      date: today,
      description: "Transferencia bancaria antes del mediodía.",
      priority: "alta",
      visibility: "privada",
      reminders: ["mismo_dia"],
    },
    {
      ...base,
      id: "a10",
      type: "tarea",
      title: "Cita médica anual",
      companyId: null,
      ownerId: "nuvia",
      date: d(7),
      time: "07:45",
      priority: "media",
      visibility: "privada",
      reminders: ["1_dia"],
    },
    {
      ...base,
      id: "a11",
      type: "vencimiento",
      title: "Declaración de ITBMS",
      companyId: "mr",
      ownerId: "liz",
      sharedWith: ["nuvia"],
      date: d(6),
      description: "Presentar declaración mensual de ITBMS en e‑Tax.",
      priority: "alta",
      visibility: "empresa",
      reminders: ["3_dias", "1_dia"],
      recurrence: "mensual",
    },
    {
      ...base,
      id: "a12",
      type: "tarea",
      title: "Actualizar listado de propiedades disponibles",
      companyId: "ramac",
      ownerId: "jose",
      date: d(-1),
      priority: "media",
      visibility: "empresa",
      status: "completada",
    },
    {
      ...base,
      id: "a13",
      type: "tarea",
      title: "Enviar factura a cliente de consultoría",
      companyId: "solidez",
      ownerId: "vivian",
      date: d(-3),
      priority: "alta",
      visibility: "empresa",
      status: "pendiente",
      reminders: ["mismo_dia"],
    },
    {
      ...base,
      id: "a14",
      type: "reunion",
      title: "Llamada con cliente corporativo — asesoría legal",
      companyId: "plp",
      ownerId: "michelle",
      sharedWith: ["nuvia"],
      date: today,
      time: "16:00",
      priority: "media",
      visibility: "compartida",
    },
  ];

  const notes: Note[] = [
    {
      id: "n1",
      title: "Documentos pendientes del cliente Rodríguez",
      content: "Falta carta de trabajo y últimos 3 talonarios. Recordar pedirlos en la próxima llamada.",
      companyId: "ramac",
      authorId: "michelle",
      createdAt: ts,
    },
    {
      id: "n2",
      title: "Idea: plantilla de cierre mensual",
      content: "Crear una lista de verificación estándar para el cierre de cada empresa y reutilizarla cada mes.",
      companyId: "mr",
      authorId: "nuvia",
      createdAt: ts,
    },
    {
      id: "n3",
      title: "Contactos de aseguradoras",
      content: "Assa – Lic. Pérez. Mapfre – Sra. González. Pedir cotización con cobertura de responsabilidad civil.",
      companyId: "plp",
      authorId: "nuvia",
      createdAt: ts,
    },
    {
      id: "n4",
      title: "Compras para la oficina",
      content: "Tóner de impresora, papel tamaño legal y carpetas.",
      companyId: null,
      authorId: "nuvia",
      createdAt: ts,
    },
  ];

  const incidents: SupportIncident[] = [
    {
      id: "inc-1",
      code: "INC-2026-001",
      memberId: "liz",
      kind: "recordatorios",
      severity: "leve",
      status: "resuelto",
      title: "Confirmar que la alerta de SIPE se envíe a las 8:00 AM",
      message: "Verificar que el aviso automático del día 15 llegue temprano en la mañana por correo y al celular.",
      page: "/tareas",
      device: "computadora",
      browser: "Chrome 128 / Windows",
      createdAt: d(-4),
      resolvedAt: d(-3),
      adminNotes: "Configurada la regla de aviso matutino a las 8:00 AM en el módulo de integraciones.",
    },
    {
      id: "inc-2",
      code: "INC-2026-002",
      memberId: "jose",
      kind: "error_tecnico",
      severity: "media",
      status: "abierto",
      title: "Problema al intentar imprimir en tamaño carta",
      message: "Al exportar a PDF en safari móvil los márgenes quedaban muy reducidos. Sugiero añadir vista de resumen gerencial.",
      page: "/imprimir",
      device: "celular",
      browser: "Safari iOS 18",
      createdAt: d(-1),
      adminNotes: "En desarrollo el nuevo generador de resumen gerencial con gráficos ejecutivos.",
    },
  ];

  const quickReminders: QuickReminder[] = [
    {
      id: "qr-1",
      title: "Confirmar recepción de comprobante fiscal con Liz",
      dueTime: "11:30",
      dueDate: today,
      companyId: "mr",
      completed: false,
      notifyOnBrowser: true,
      createdAt: ts,
    },
    {
      id: "qr-2",
      title: "Llamar a Notaría Cuarta antes de las 3:00 PM por escritura Rodríguez",
      dueTime: "15:00",
      dueDate: today,
      companyId: "ramac",
      completed: false,
      notifyOnBrowser: true,
      createdAt: ts,
    },
    {
      id: "qr-3",
      title: "Enviar número de cuenta bancaria a nuevo cliente",
      dueTime: "16:45",
      dueDate: today,
      companyId: "solidez",
      completed: true,
      notifyOnBrowser: false,
      createdAt: ts,
    },
  ];

  return {
    currentUserId: "nuvia",
    orgId: "grupo-nuvia",
    orgName: "Grupo Nuvia",
    organizations: [{ id: "grupo-nuvia", name: "Grupo Nuvia" }],
    users: USERS,
    companies: COMPANIES,
    activities,
    notes,
    incidents,
    integrations: DEFAULT_INTEGRATIONS,
    quickReminders,
    dbConfig: DEFAULT_DB_CONFIG,
    sslConfig: DEFAULT_SSL_CONFIG,
    adminLogs: INITIAL_ADMIN_LOGS,
    themeMode: "light",
    isAuthenticated: true,
  };
}
